# Generated by Django 3.2.19 on 2025-03-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_qr_code_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
