# Generated by Django 3.2.19 on 2025-03-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_qr_code_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
